### ISSUE TITLE
installation in MacOS

### ISSUE THREAD

**Issue by DavidGO464** [wzthu/Rbowtie2#6]
Hi!

everytime that I try to install Rhisat2, they ask me about accepting c/c++; when I write no... installation is terminated but when I write "Yes"... al theses errors appears.

How can I proceed in this situation. I am using MacOS apple silicon M1

kind regards
![111](https://user-images.githubusercontent.com/87618961/218324337-957abe57-ceb0-480a-8746-7afcfb882ad3.jpg)
![222](https://user-images.githubusercontent.com/87618961/218324380-680dd00f-16b5-479e-82cf-c1a03a367af2.jpg)

**Comment by martin-g** [comment]
I see only warnings, no errors.

**Comment by DavidGO464** [comment]
> I see only warnings, no errors.

it seems that installing gfortran or xquartz (this may help somehow: https://github.com/xia-lab/MetaboAnalystR/issues/259)  

or gdal (via brew) or terminate with the problem
